# GitHub Sponsors configuration
# Configure sponsorship options for LionAGI QE Fleet

# GitHub Sponsors
# github: [username1, username2]

# Patreon
# patreon: username

# Open Collective
# open_collective: project-name

# Ko-fi
# ko_fi: username

# Tidelift
# tidelift: pypi/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Other sponsorship options
# custom: ['https://paypal.me/username', 'https://example.com/donate']

# Note: Uncomment and configure the sponsorship options you want to enable
# Remove this file if you don't want to accept sponsorships
